@TodoApi_HostAddress = http://localhost:5142

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{TodoApi_HostAddress}}/api/todoitems

###

@id=69b6b567a86b589e90d9d3de
GET {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###
PUT {{TodoApi_HostAddress}}/api/todoitems/69b6b567a86b589e90d9d3de
Content-Type: application/json

{
  "id": "69b6b567a86b589e90d9d3de",
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{TodoApi_HostAddress}}/api/todoitems/69b6b567a86b589e90d9d3de

###